# Generated by Django 4.1.4 on 2023-12-20 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_user_confirmation_code_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('887571cf-0a94-4c98-a79c-6c653bd4d46a'), max_length=150),
        ),
    ]
